
/* Generated by fzmparser version 2.2 --- DO NOT EDIT! */

/* Uses following resources: */
/* [6 events, 2+0 states, 1 inputs, 3 outputs, 5 match regs, 0 capture regs] */

#include "sct_fsm.h"


void sct_fsm_init (void)
{
LPC_SCT->CONFIG = (LPC_SCT->CONFIG & ~0x00060001) | 0x00020001; /* AUTOLIMIT_L UNIFIED */

/* MATCH/CAPTURE registers */

  /* L counter uses AUTOLIMIT (match register 0) */

/* Unified counter - register side L is used and accessed as 32 bit value, reg H is not used */
LPC_SCT->REGMODE_L = 0x00000000;         /* U: 5x MATCH, 0x CAPTURE, 0 unused */

LPC_SCT->MATCH[0].U = delay;             /* match_cycle */
LPC_SCT->MATCHREL[0].U = delay;
LPC_SCT->MATCH[1].U = C_match_green_OFF;             /* match_green_OFF */
LPC_SCT->MATCHREL[1].U = C_match_green_OFF;
LPC_SCT->MATCH[2].U = C_match_green_ON;             /* match_green_ON */
LPC_SCT->MATCHREL[2].U = C_match_green_ON;
LPC_SCT->MATCH[3].U = C_match_red_OFF;             /* match_red_OFF */
LPC_SCT->MATCHREL[3].U = C_match_red_OFF;
LPC_SCT->MATCH[4].U = C_match_red_ON;             /* match_red_ON */
LPC_SCT->MATCHREL[4].U = C_match_red_ON;

/* OUTPUT registers */
LPC_SCT->OUT[0].SET = 0x0000000B;        /* LED_green */
LPC_SCT->OUT[0].CLR = 0x00000004;
LPC_SCT->OUT[1].SET = 0x00000029;        /* LED_red */
LPC_SCT->OUT[1].CLR = 0x00000010;
LPC_SCT->OUT[2].SET = 0x00000009;        /* LED_yellow */
LPC_SCT->OUT[2].CLR = 0x00000000;
  /* Unused outputs must not be affected by any event */
LPC_SCT->OUT[3].SET = 0;
LPC_SCT->OUT[3].CLR = 0;
LPC_SCT->OUTPUT = (LPC_SCT->OUTPUT & ~0x00000000) | 0x00000007;

/* Conflict resolution register */

/* EVENT registers */
LPC_SCT->EVENT[0].CTRL = 0x0000F000;     /* U: --> state state_1 */
LPC_SCT->EVENT[0].STATE = 0x00000001;
LPC_SCT->EVENT[1].CTRL = 0x00005003;     /* U: --> state U_ENTRY */
LPC_SCT->EVENT[1].STATE = 0x00000001;
LPC_SCT->EVENT[2].CTRL = 0x00005004;     /* U: --> state U_ENTRY */
LPC_SCT->EVENT[2].STATE = 0x00000001;
LPC_SCT->EVENT[3].CTRL = 0x00007C00;     /* U: --> state U_ENTRY */
LPC_SCT->EVENT[3].STATE = 0x00000002;
LPC_SCT->EVENT[4].CTRL = 0x0000D002;     /* U: --> state state_1 */
LPC_SCT->EVENT[4].STATE = 0x00000002;
LPC_SCT->EVENT[5].CTRL = 0x0000D001;     /* U: --> state state_1 */
LPC_SCT->EVENT[5].STATE = 0x00000002;

/* STATE registers */
LPC_SCT->STATE_L = 0;

/* state names assignment: */
  /* State U 0: U_ENTRY */
  /* State U 1: state_1 */

/* CORE registers */
LPC_SCT->START_L = 0x00000000;
LPC_SCT->STOP_L =  0x00000000;
LPC_SCT->HALT_L =  0x00000000;
LPC_SCT->LIMIT_L = 0x00000000;
LPC_SCT->EVEN =    0x00000009;

}
