/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v8.0
processor: LPC812
package_id: LPC812M101JDH20
mcu_data: ksdk2_0
processor_version: 8.0.2
pin_labels:
- {pin_num: '17', pin_signal: PIO0_7, label: LED_BLUE, identifier: LED_BLUE}
- {pin_num: '10', pin_signal: PIO0_16, label: LED_GREEN, identifier: LED_GREEN}
- {pin_num: '1', pin_signal: PIO0_17, label: LED_RED, identifier: LED_RED}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_swm.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_GpioInit();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_GpioInit:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '14', peripheral: SYSCON, signal: XTALIN, pin_signal: PIO0_8/XTALIN, mode: inactive}
  - {pin_num: '13', peripheral: SYSCON, signal: XTALOUT, pin_signal: PIO0_9/XTALOUT, mode: inactive}
  - {pin_num: '4', peripheral: SYSCON, signal: RESETN, pin_signal: RESETN/PIO0_5}
  - {pin_num: '5', peripheral: USART0, signal: TXD, pin_signal: PIO0_4}
  - {pin_num: '19', peripheral: USART0, signal: RXD, pin_signal: PIO0_0/ACMP_I1}
  - {pin_num: '17', peripheral: GPIO, signal: 'PIO0, 7', pin_signal: PIO0_7}
  - {pin_num: '10', peripheral: GPIO, signal: 'PIO0, 16', pin_signal: PIO0_16}
  - {pin_num: '1', peripheral: GPIO, signal: 'PIO0, 17', pin_signal: PIO0_17}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_GpioInit
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_GpioInit(void)
{
    /* Enables clock for switch matrix.: Enable. */
    CLOCK_EnableClock(kCLOCK_Swm);

    IOCON->PIO[14] = ((IOCON->PIO[14] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_MODE_MASK)))

                      /* Selects function mode (on-chip pull-up/pull-down resistor control).: Inactive. Inactive (no
                       * pull-down/pull-up resistor enabled). */
                      | IOCON_PIO_MODE(PIO0_8_MODE_INACTIVE));

    IOCON->PIO[13] = ((IOCON->PIO[13] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_MODE_MASK)))

                      /* Selects function mode (on-chip pull-up/pull-down resistor control).: Inactive. Inactive (no
                       * pull-down/pull-up resistor enabled). */
                      | IOCON_PIO_MODE(PIO0_9_MODE_INACTIVE));

    /* USART0_TXD connect to P0_4 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_TXD, kSWM_PortPin_P0_4);

    /* USART0_RXD connect to P0_0 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_RXD, kSWM_PortPin_P0_0);

    /* XTALIN connect to P0_8 */
    SWM_SetFixedPinSelect(SWM0, kSWM_XTALIN, true);

    /* XTALOUT connect to P0_9 */
    SWM_SetFixedPinSelect(SWM0, kSWM_XTALOUT, true);

    /* RESETN connect to P0_5 */
    SWM_SetFixedPinSelect(SWM0, kSWM_RESETN, true);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
